# CI Pipeline: Build Java App + Build & Push Docker Image
name: Java CI with Maven

# Trigger workflow on push & PR to GH-Actions branch
on:
  push:
    branches: [ "GH-Actions" ]
  pull_request:
    branches: [ "GH-Actions" ]

jobs:
  build:

    # Use Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
    # Checkout source code from repository
    - uses: actions/checkout@v4

    # Install and configure Java 8
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    # Build application using Maven    
    - name: Build with Maven
      run: mvn -B clean package -Dmaven.test.skip=true --file pom.xml

    # Switch to Java 17 for Sonar
    - name: Set up JDK 17 for Sonar
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # SonarQube Scan
    - name: SonarQube Scan
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=ecart-service \
          -Dsonar.host.url=http://13.206.204.162:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ecart-service:latest .
        docker build -t ecart-service:${{ github.sha }} .

    # =========================
    # 🔹 DOCKER HUB
    # =========================

    # Login to Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Tag for Docker Hub
    - name: Tag for Docker Hub
      run: |
        docker tag ecart-service:latest rowdygani/ecart-service:latest
        docker tag ecart-service:${{ github.sha }} rowdygani/ecart-service:${{ github.sha }}

    # Push to Docker Hub
    - name: Push to Docker Hub
      run: |
        docker push rowdygani/ecart-service:latest
        docker push rowdygani/ecart-service:${{ github.sha }}

    # =========================
    # 🔹 AWS ECR
    # =========================

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Tag for ECR
    - name: Tag for ECR
      run: docker tag ecart-service:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/rowdyops-ecart-service:${{ github.sha }}

    # Push to ECR
    - name: Push to ECR
      run: docker push ${{ steps.login-ecr.outputs.registry }}/rowdyops-ecart-service:${{ github.sha }}